variable is-eks-cluster-enabled{}
variable "cluster-name" { }
variable "cluster-version" { }
variable "endpoint-public-access" { }
variable "endpoint-private-access" { }
variable "cidr_block" { }
variable "vpc-name" { }
variable "env" { }
variable "vpc-id" { }
variable "igw-name" { }
variable "pub-subnet-count" { }
variable "pub-cidr-block" { }
variable "pub-sub-name" { }
variable "pri-subnet-count" { }
variable "pri-availability-zone" { }
variable "pri-sub-name" { }
variable "pub-availability-zone" { }
variable "pri-cidr-block" { }
variable "public-rt-name" { }
variable "eip-name" { }
variable "ngw-name" { }
variable "private-rt-name" { }
variable "eks-sg" { }
variable "is-eks-nodegroup-enabled" { }
variable "addon" { }
variable "max_capacity_on_demand" { }
variable "min_capacity_on_demand" { }
variable "desired_capacity_on_demand" { }
variable "ondemand__instance_type" { }
variable "desired_capacity_spot_node" { }
variable "min_capacity_spot_node" { }
variable "max_capacity_spot_node" { }