variable is_eks_cluster_enabled{}
variable "cluster_name" { }
variable "cluster_version" { }
variable "endpoint_public_access" { }
variable "endpoint_private_access" { }
variable "cidr_block" { }
variable "vpc_name" { }
variable "env" { }
variable "igw_name" { }
variable "pub_subnet_count" { }
variable "pub_cidr_block" { }
variable "pub_sub_name" { }
variable "pri_subnet_count" { }
variable "pri_availability_zone" { }
variable "pri_sub_name" { }
variable "pub_availability_zone" { }
variable "pri_cidr_block" { }
variable "public_rt_name" { }
variable "eip_name" { }
variable "ngw_name" { }
variable "private_rt_name" { }
variable "eks_sg" { }
variable "is_eks_nodegroup_enabled" { }
variable "addon" { }
variable "max_capacity_on_demand" { }
variable "min_capacity_on_demand" { }
variable "desired_capacity_on_demand" { }
variable "desired_capacity_spot_node" { }
variable "min_capacity_spot_node" { }
variable "max_capacity_spot_node" { }
variable "spot_instance_type" { }
variable "ondemand_instance_type" { }